#!/usr/bin/env bash

curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
cp ~/.bashrc ~/.bashrc.old
{ curl https://raw.githubusercontent.com/zhangyuan/deploy/master/rbenv/load ; cat ~/.bashrc; } > bashrc
mv bashrc .bashrc
source .bashrc
rbenv install 2.3.0
rbenv global 2.3.0
rbenv rehash
gem install bundler --no-ri --no-rdoc
rbenv rehash
