#!/usr/bin/env bash

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

curl -L https://raw.githubusercontent.com/zhangyuan/deploy/master/vim/vimrc.sample > ~/.vimrc

vim +PluginInstall +qall
