#!/usr/bin/env bash

apt-get install pptpd iptables

echo "localip 10.21.0.1" >> /etc/pptpd.conf
echo "localip 10.21.0.1" >> /etc/pptpd.conf
echo "remoteip 10.21.0.100-200" >> /etc/pptpd.conf

echo "ms-dns 8.8.8.8" >> /etc/ppp/pptpd-options

echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

sysctl -p

iptables -t nat -A POSTROUTING -s 10.21.0.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables-rules
iptables-restore < /etc/iptables-rules

echo "Not finished yet. Please:"
echo "1. set user and password in /etc/ppp/chap-secrets"
echo "2. add iptables-restore < /etc/iptables-rules to /etc/rc.local"
